### PR TITLE
Fixes for path issues on Windows.

### PR DESCRIPTION
**Pull request by kcbanner**
Fixes https://github.com/zig-gamedev/zig-gamedev/issues/511.

This is an alternative to the solution here https://github.com/zig-gamedev/zig-gamedev/pull/514, which can be used until the issues with the build system preventing dependency use are resolved.

Changes:
- Change build scripts to use `cwd_relative` when `thisDIr()` is used
- FIxup atan2 usage in instanced_pills_wgpu
- Fixup @ptrCast of optional slice causing a compiler panic (https://github.com/ziglang/zig/issues/19168)

### CODE REVIEW

**Comment by hazeycode** [comment]
Since these changes depend on a new version of Zig than our pinned version (0.12.0-dev.2063+804cee3b9) I have retargeted this to the unstable branch. Which compiler revisionary you using?

**Comment by kcbanner** [comment]
Ah thanks! I'm using latest master, 0.12.0-dev.3152+90c1a2c41

**Comment by hazeycode** [comment]
I have updated the .zigversion file on the unstable branch but I think this needs rebasing for CI checks to use it.

**Comment by hazeycode** [comment]
Resolved by https://github.com/zig-gamedev/zig-gamedev/pull/518

**Pull request closed without merging**
