### PR TITLE
Update imgui to 1.89.9-docking and implot to 0.16

### PR DESCRIPTION
**Pull request by dstrachan**

### CODE REVIEW

**Comment by michal-z** [comment]
Thanks for the PR.

Quick question. We have some custom changes/fixes in the renderer (I mark them with `mziulek` tag in the code). Have you ported them to the new code?

**Comment by dstrachan** [comment]
I ported all that I managed to find:

- imgui_impl_dx12.cpp
  - PFN_D3D12_SERIALIZE_ROOT_SIGNATURE is not defined when using MinGW
- imgui_impl_glfw.cpp
  - DpiScale in ImGui_ImplGlfw_Data
- imgui_impl_wgpu.cpp
  - Fixes 'Popups and Modal windows->Modals->Stacked modals..' from showDemoWindow().
  - Explicitly release the memory reserved in ImGui_ImplWGPU_Init().

I also added in the header files for the glfw and wgpu backends to simplify future upgrades as the only changes in the header files should be extern "C" lines.

**Comment by michal-z** [comment]
Great work, thanks a lot! Will look at it tomorrow.

**Comment by michal-z** [comment]
I get a compile error:
```
zig build-lib zgui Debug native: error: error(compilation): clang failed with stderr: C:\Development\projects\zig-gamedev\libs\zgui\libs\imgui\backends\imgui_impl_glfw.cpp:938:22: error: use of undeclared identifier 'ceil'
C:\Development\projects\zig-gamedev\libs\zgui\libs\imgui\backends\imgui_impl_glfw.cpp:939:22: error: use of undeclared identifier 'ceil'
```

**Comment by dstrachan** [comment]
I've fixed the compiler error on Windows and updated the Style struct to add docking changes.

The scrollbar is now green but still thin, I'm struggling to figure out why. I'll continue to investigate.

**Comment by michal-z** [comment]
I will also look a this, thanks!

**Comment by ngortheone** [comment]
Imgui 1.90 is already out. Maybe worth jumping straight to the latest release ?

**Comment by hazeycode** [comment]
Superseded by https://github.com/zig-gamedev/zig-gamedev/pull/537

**Pull request closed without merging**
