### PR TITLE
add zphysics instanced cubes d3d12 sample

### PR DESCRIPTION
**Pull request by Pyrolistical**
See https://github.com/zig-gamedev/zig-gamedev/blob/2fab51766f6525a44f84b679c69bcf0fbafc7af3/samples/zphysics_instanced_cubes_d3d12/README.md

### CODE REVIEW

**Comment by hazeycode** [comment]
Nice! This works great on native Windows. However, the build is failing for some reason when cross-compiling from Linux. I did notice also that although the window can be resized, the frame buffer size is unchanged.

**Comment by Pyrolistical** [comment]
I'll fix the framebuffer failing to resize

**Comment by Pyrolistical** [comment]
> However, the build is failing when cross-compiling from Linux

I'll get Ubuntu installed and repo

**Comment by hazeycode** [comment]
> > However, the build is failing when cross-compiling from Linux
> 
> If we care about this, should this not be an github action?

Yes, good point. I will update the CI script.

**Comment by Pyrolistical** [comment]
Thanks for adding the CI, but what the heck is `zwin320`

**Comment by hazeycode** [comment]
I think this is to do with target mismatch. In triangle/build.zig, the zpix target option is specified but it was using the default here.

It turns out that zpix does not even need to depend on zwin32 at all. I have removed the dependency. Can you try reintroducing zpix to your sample app and rebasing on main branch?

**Comment by hazeycode** [comment]
Merged this here in https://github.com/zig-gamedev/zig-gamedev/pull/684 (GitHub wouldn't let me edit this PR)

Thanks!

**Pull request closed without merging**
