### PR TITLE
Jolt Physics updated to 5.1.0 release

### PR DESCRIPTION
**Pull request by a-day-old-bagel**
In response to #622, as well as my own desire to use newer releases of Jolt.

This is an assorted bag of changes. I've only had access to a Windows machine over the past few days, so we may want to get some of you to also test this on your systems before considering it a mature PR, if we're not confident in the results of the CI alone.

I've probably missed something somewhere, but after testing all the things I can think of, I haven't found any more changes that need to take place on my own.

Part of the upgrade involved implementing a realloc function for Jolt to call, and I've just put in a naive approach that might need a second pair of eyes. I never used to use realloc much in C, so I just did it how I thought most logical, and so far all the tests run, and my application also runs, and I can confirm Jolt 5.1.0 is calling realloc quite a bit. And sometimes, it does successfully resize an allocation, so whatever benefit Jolt's author thought might be available via resizing allocations should be possible through our zphysics allocator implementation.

All I have done is maintain our currently exposed API feature set, and gotten it to run on top of 5.1.0, to be clear. Jolt has added a bunch of soft body stuff, but I haven't done any additional work to actually expose any of that. Only to bring our existing exposed API bits into sync.

Please let me know if there's anything here we'd prefer to do differently.

### CODE REVIEW

**Comment by michal-z** [comment]
For `realloc()` you could use `Allocator.realloc()` which would simplify your implementation. `zmesh` does similar thing here:
https://github.com/zig-gamedev/zig-gamedev/blob/main/libs/zmesh/src/memory.zig#L71

**Comment by a-day-old-bagel** [comment]
Ok, I switched to using the approach from zmesh, and it did seem to work just the same, so I must have just bumbled around in the wrong direction before when trying those methods.

**Comment by hazeycode** [comment]
Tested `physics_test_wgpu` and `monolith` sample apps with these changes on an Intel Mac running macOS 13.5. Everything appears to be working as before. Changes look good too. Along with passing tests, that's enough for me to happily merge this. Missing APIs can be added later. If there are any unearthed errors we should expand the coverage of the tests and/or the sample app repertoire.  

Thank you for this. It looks like it took quite a lot of effort.

**Review by hazeycode — APPROVED** [review]
Tested `physics_test_wgpu` and `monolith` sample apps with these changes on an Intel Mac running macOS 13.5. Everything appears to be working as before. Changes look good too. Along with passing tests, that's enough for me to happily merge this. Missing APIs can be added later. If there are any unearthed errors we should expand the coverage of the tests and/or the sample app repertoire.  

Thank you for this. It looks like it took quite a lot of effort.

**Pull request merged**
