### PR TITLE
minimal_glfw_d3d12 sample

### PR DESCRIPTION
**Pull request by Pyrolistical**
I was able to strip out all the windowing usage of win32 out of the `minimal_d3d12` sample and replace it with zglfw + zd3d12.

I ran into a type conflict.
1. [`zwin32.dxgi.SWAP_CHAIN_DESC.OutputWindow`](https://github.com/zig-gamedev/zig-gamedev/blob/a2839f8dbc068042880168d1586b0d57f1789f23/libs/zwin32/src/dxgi.zig#L527) is type `zwin32.HWMD`, which is `*opaque {}`
2. [`zglfw.native.getWin32Window`](https://github.com/zig-gamedev/zig-gamedev/blob/a2839f8dbc068042880168d1586b0d57f1789f23/libs/zglfw/src/zglfw.zig#L1001)  returns a `std.os.windows.HWND`

I resolved the conflict by redefining `zwin32.HWMD` to be `std.os.windows.HWND`. This worked and `zig build test` works, but is it correct?

I also need help testing this on Linux. It should still work.

### CODE REVIEW

**Comment by Pyrolistical** [comment]
Here is diff between `minimal_d3d12.zig` and `minimal_glfw_d3d12.zig`
```
diff --git "a/samples\\minimal_d3d12\\src\\minimal_d3d12.zig" "b/samples\\minimal_glfw_d3d12\\src\\minimal_glfw_d3d12.zig"
index b63ed443..d514f5d0 100644
--- "a/samples\\minimal_d3d12\\src\\minimal_d3d12.zig"
+++ "b/samples\\minimal_glfw_d3d12\\src\\minimal_glfw_d3d12.zig"
@@ -1,4 +1,5 @@
 const std = @import("std");
+const glfw = @import("zglfw");
 const zwin32 = @import("zwin32");
 const w32 = zwin32.w32;
 const dxgi = zwin32.dxgi;
@@ -9,96 +10,22 @@ const hrPanicOnFail = zwin32.hrPanicOnFail;
 pub export const D3D12SDKVersion: u32 = 610;
 pub export const D3D12SDKPath: [*:0]const u8 = ".\\d3d12\\";
 
-const window_name = "zig-gamedev: minimal d3d12";
-
-fn processWindowMessage(
-    window: w32.HWND,
-    message: w32.UINT,
-    wparam: w32.WPARAM,
-    lparam: w32.LPARAM,
-) callconv(w32.WINAPI) w32.LRESULT {
-    switch (message) {
-        w32.WM_KEYDOWN => {
-            if (wparam == w32.VK_ESCAPE) {
-                w32.PostQuitMessage(0);
-                return 0;
-            }
-        },
-        w32.WM_GETMINMAXINFO => {
-            var info: *w32.MINMAXINFO = @ptrFromInt(@as(usize, @intCast(lparam)));
-            info.ptMinTrackSize.x = 400;
-            info.ptMinTrackSize.y = 400;
-            return 0;
-        },
-        w32.WM_DESTROY => {
-            w32.PostQuitMessage(0);
-            return 0;
-        },
-        else => {},
-    }
-    return w32.DefWindowProcA(window, message, wparam, lparam);
-}
-
-fn createWindow(width: u32, height: u32) w32.HWND {
-    const winclass = w32.WNDCLASSEXA{
-        .style = 0,
-        .lpfnWndProc = processWindowMessage,
-        .cbClsExtra = 0,
-        .cbWndExtra = 0,
-        .hInstance = @ptrCast(w32.GetModuleHandleA(null)),
-        .hIcon = null,
-        .hCursor = w32.LoadCursorA(null, @ptrFromInt(32512)),
-        .hbrBackground = null,
-        .lpszMenuName = null,
-        .lpszClassName = window_name,
-        .hIconSm = null,
-    };
-    _ = w32.RegisterClassExA(&winclass);
-
-    const style = w32.WS_OVERLAPPEDWINDOW;
-
-    var rect = w32.RECT{
-        .left = 0,
-        .top = 0,
-        .right = @intCast(width),
-        .bottom = @intCast(height),
-    };
-    _ = w32.AdjustWindowRectEx(&rect, style, w32.FALSE, 0);
-
-    const window = w32.CreateWindowExA(
-        0,
-        window_name,
-        window_name,
-        style + w32.WS_VISIBLE,
-        w32.CW_USEDEFAULT,
-        w32.CW_USEDEFAULT,
-        rect.right - rect.left,
-        rect.bottom - rect.top,
-        null,
-        null,
-        winclass.hInstance,
-        null,
-    ).?;
-
-    std.log.info("Application window created", .{});
-
-    return window;
-}
+const window_name = "zig-gamedev: minimal glfw d3d12";
 
 pub fn main() !void {
-    _ = w32.CoInitializeEx(null, w32.COINIT_MULTITHREADED);
-    defer w32.CoUninitialize();
-
-    _ = w32.SetProcessDPIAware();
+    try glfw.init();
+    defer glfw.terminate();
 
-    const window = createWindow(1600, 1200);
+    glfw.windowHintTyped(.client_api, .no_api);
+    const glfw_window = try glfw.Window.create(1600, 1200, window_name, null);
+    defer glfw_window.destroy();
 
-    var dx12 = Dx12State.init(window);
+    var dx12 = try Dx12State.init(glfw_window);
     defer dx12.deinit();
 
     const root_signature: *d3d12.IRootSignature, const pipeline: *d3d12.IPipelineState = blk: {
-        const vs_cso = @embedFile("./minimal_d3d12.vs.cso");
-        const ps_cso = @embedFile("./minimal_d3d12.ps.cso");
+        const vs_cso = @embedFile("./minimal_glfw_d3d12.vs.cso");
+        const ps_cso = @embedFile("./minimal_glfw_d3d12.ps.cso");
 
         var pso_desc = d3d12.GRAPHICS_PIPELINE_STATE_DESC.initDefault();
         pso_desc.DepthStencilState.DepthEnable = w32.FALSE;
@@ -131,37 +58,28 @@ pub fn main() !void {
     defer _ = root_signature.Release();
 
     var frac: f32 = 0.0;
-    var frac_delta: f32 = 0.005;
+    var frac_delta: f32 = 0.0001;
 
-    var window_rect: w32.RECT = undefined;
-    _ = w32.GetClientRect(window, &window_rect);
+    var framebuffer_size = glfw_window.getFramebufferSize();
 
     //
     // Main Loop
     //
-    main_loop: while (true) {
+    main_loop: while (!glfw_window.shouldClose() and glfw_window.getKey(.escape) != .press) {
+        glfw.pollEvents();
         {
-            var message = std.mem.zeroes(w32.MSG);
-            while (w32.PeekMessageA(&message, null, 0, 0, w32.PM_REMOVE) == w32.TRUE) {
-                _ = w32.TranslateMessage(&message);
-                _ = w32.DispatchMessageA(&message);
-                if (message.message == w32.WM_QUIT) {
-                    break :main_loop;
-                }
-            }
-
-            var rect: w32.RECT = undefined;
-            _ = w32.GetClientRect(window, &rect);
-            if (rect.right == 0 and rect.bottom == 0) {
+            if (glfw_window.getAttribute(.iconified)) {
                 // Window is minimized
-                w32.Sleep(10);
+                const ns_in_ms: u64 = 1_000_000;
+                std.time.sleep(10 * ns_in_ms);
                 continue :main_loop;
             }
 
-            if (rect.right != window_rect.right or rect.bottom != window_rect.bottom) {
-                rect.right = @max(1, rect.right);
-                rect.bottom = @max(1, rect.bottom);
-                std.log.info("Window resized to {d}x{d}", .{ rect.right, rect.bottom });
+            var next_framebuffer_size = glfw_window.getFramebufferSize();
+            if (next_framebuffer_size[0] != framebuffer_size[0] or next_framebuffer_size[1] != framebuffer_size[1]) {
+                next_framebuffer_size[0] = @max(1, next_framebuffer_size[0]);
+                next_framebuffer_size[1] = @max(1, next_framebuffer_size[1]);
+                std.log.info("Window resized to {d}x{d}", .{ next_framebuffer_size[0], next_framebuffer_size[1] });
 
                 dx12.finishGpuCommands();
 
@@ -186,7 +104,7 @@ pub fn main() !void {
                     );
                 }
             }
-            window_rect = rect;
+            framebuffer_size = next_framebuffer_size;
         }
 
         const command_allocator = dx12.command_allocators[dx12.frame_index];
@@ -197,16 +115,16 @@ pub fn main() !void {
         dx12.command_list.RSSetViewports(1, &[_]d3d12.VIEWPORT{.{
             .TopLeftX = 0.0,
             .TopLeftY = 0.0,
-            .Width = @floatFromInt(window_rect.right),
-            .Height = @floatFromInt(window_rect.bottom),
+            .Width = @floatFromInt(framebuffer_size[0]),
+            .Height = @floatFromInt(framebuffer_size[1]),
             .MinDepth = 0.0,
             .MaxDepth = 1.0,
         }});
         dx12.command_list.RSSetScissorRects(1, &[_]d3d12.RECT{.{
             .left = 0,
             .top = 0,
-            .right = @intCast(window_rect.right),
-            .bottom = @intCast(window_rect.bottom),
+            .right = @intCast(framebuffer_size[0]),
+            .bottom = @intCast(framebuffer_size[1]),
         }});
 
         const back_buffer_index = dx12.swap_chain.GetCurrentBackBufferIndex();
@@ -289,7 +207,9 @@ const Dx12State = struct {
 
     const num_frames = 2;
 
-    fn init(window: w32.HWND) Dx12State {
+    fn init(glfw_window: *glfw.Window) !Dx12State {
+        const window = try glfw.native.getWin32Window(glfw_window);
+
         //
         // DXGI Factory
         //
@@ -317,14 +237,8 @@ const Dx12State = struct {
         //
         var device: *d3d12.IDevice9 = undefined;
         if (d3d12.CreateDevice(null, .@"11_0", &d3d12.IID_IDevice9, @ptrCast(&device)) != w32.S_OK) {
-            _ = w32.MessageBoxA(
-                window,
-                "Failed to create Direct3D 12 Device. This applications requires graphics card " ++
-                    "with DirectX 12 Feature Level 11.0 support.",
-                "Your graphics card driver may be old",
-                w32.MB_OK | w32.MB_ICONERROR,
-            );
-            w32.ExitProcess(0);
+            @panic("Your graphics card driver may be old. Failed to create Direct3D 12 Device. " ++
+                "This applications requires graphics card with DirectX 12 Feature Level 11.0 support.");
         }
 
         std.log.info("D3D12 device created", .{});
@@ -345,15 +259,14 @@ const Dx12State = struct {
         //
         // Swap Chain
         //
-        var rect: w32.RECT = undefined;
-        _ = w32.GetClientRect(window, &rect);
+        const framebuffer_size = glfw_window.getFramebufferSize();
 
         var swap_chain: *dxgi.ISwapChain3 = undefined;
         {
             var desc = dxgi.SWAP_CHAIN_DESC{
                 .BufferDesc = .{
-                    .Width = @intCast(rect.right),
-                    .Height = @intCast(rect.bottom),
+                    .Width = @intCast(framebuffer_size[0]),
+                    .Height = @intCast(framebuffer_size[1]),
                     .RefreshRate = .{ .Numerator = 0, .Denominator = 0 },
                     .Format = .R8G8B8A8_UNORM,
                     .ScanlineOrdering = .UNSPECIFIED,
```

**Comment by hazeycode** [comment]
> I resolved the conflict by redefining zwin32.HWMD to be std.os.windows.HWND. This worked and zig build test works, but is it correct?

Yes, I think this is correct. But worth checking that the other win32 samples still work.

> I also need help testing this on Linux. It should still work.

I will test on Linux as soon as I can.

**Comment by Pyrolistical** [comment]
> > I resolved the conflict by redefining zwin32.HWMD to be std.os.windows.HWND. This worked and zig build test works, but is it correct?
> 
> Yes, I think this is correct.

Should we just inline `std.os.windows.HWND` to all places that use `zwin32.HWMD`?

**Comment by hazeycode** [comment]
> > > I resolved the conflict by redefining zwin32.HWMD to be std.os.windows.HWND. This worked and zig build test works, but is it correct?
> 
> > 
> 
> > Yes, I think this is correct.
> 
> 
> 
> Should we just inline `std.os.windows.HWND` to all places that use `zwin32.HWMD`?

It would probably be better for readability yes, especially in function decls

**Pull request merged**
