### PR TITLE
zgui: Add option to not use implot

### PR DESCRIPTION
**Pull request by iacore**
I'd say it's better to not merge this for two weeks. Who knows what other change is to come?

### CODE REVIEW

**Comment by hazeycode** [comment]
Hey @iacore what's the intention here? Does this fix a particular issue for you?

**Comment by iacore** [comment]
The issue back then was that building implot caused some trouble, so I had to left it out of the build.

**Comment by hazeycode** [comment]
> The issue back then was that building implot caused some trouble, so I had to left it out of the build.

I guess there could be symbol clashes depending on how you are compiling things.

The changes look good to me. Is this ready to merge?

**Comment by iacore** [comment]
> Is this ready to merge?

yes

**Pull request merged**
