### PR TITLE
Up Zig to 0.12.0-dev.3180+83e578a18

### PR DESCRIPTION
**Pull request by hazeycode**
Upgrading to next nominated version...

### CODE REVIEW

**Comment by jcalabro** [comment]
Hello! One thing I noticed when testing out this branch is that symbol names from Tracy are mangled to all by one name:

image

Not all my zones are named `serveRequests`, only one of them is :smile:

**Comment by hazeycode** [comment]
Hey @jcalabro thanks for the heads up. I'll look into this.

**Comment by Avokadoen** [comment]
So it seems like the issue @jcalabro describes is in zig, not in ztracy? 
ztracy doesnt have any changes that should have broken tracy in this manner as far as I can tell (the issue is present on the main branch as well)

**Comment by hazeycode** [comment]
Skipping this version and instead going with https://github.com/zig-gamedev/zig-gamedev/pull/578
The branch will be left intact for now for anyone using the current Mach nominated version.

**Pull request closed without merging**
