### PR TITLE
fix(zgui): 'comptime var' is redundant in comptime scope

### PR DESCRIPTION
**Pull request by tjk**

### CODE REVIEW

**Comment by hazeycode** [comment]
Thanks for the PR. Which version of the compiler are you using?

**Comment by OndraVoves** [comment]
A have same problem on current zig master `0.12.0-dev.2741+d7563a775`

**Comment by tjk** [comment]
(Sorry for not responding earlier, I was using the 'blessed' mach version `0.12.0-dev.2729+0c725a354`)

**Comment by hazeycode** [comment]
No problem, thanks for the info ❤️

**Pull request merged**
